### ISSUE TITLE
借用前端UI写了一个go-mir的demo

### ISSUE THREAD

**Issue by alimy** [taoes/SimpleDocker#1]
hi，借用老铁的前端UI撸了一个[go-mir](https://github.com/alimy/mir 'mir')的demo用于介绍如何使用mir开发web应用。
我对前端UI开发非常陌生，无意间在开源中国看到老铁这个有意思的项目，正好也想完整介绍如何使用mir开发一个可以看见效果的web应用，就借老铁的前端UI一用，撸了[Mirage](https://github.com/alimy/mirage 'Mirage-幻影')这个go-mir的演示项目，非常感谢老铁！

**Comment by alimy** [comment]
之前有在公司使用beego开发项目，效果也是非常Ok的，但个人对前后端分离的项目，后端只提供RESTful API，还是偏向于使用gin这种轻量级框架，搭配[go-mir](https://github.com/alimy/mir)使用面向接口编程的范式来组织代码，效果非常好，建议老铁也试试这种范式开发项目。

**Comment by taoes** [comment]
可以的，很棒 👍🏻 ，可以随便使用和修改，只要遵守GPL协议即可 ~

**Comment by taoes** [comment]
好的，我研究下，目前主要是使用 Java 开发项目，之所以使用Go语言开发，是因为Docker的开发语言是Go，所以在后续的拓展和SDK上更方便，感谢！

**Comment by alimy** [comment]
你的项目非常nice，也非常希望项目一直开发下去，功能越来越完善。本人一直忙于公司业务，空闲时间比较少，只能撸一个demo出来，有空也会贡献代码到这个项目一起完善功能，哈哈哈。

**Comment by taoes** [comment]
> 你的项目非常nice，也非常希望项目一直开发下去，功能越来越完善。一直忙于公司业务，空闲时间比较少，只能撸一个demo出来，有空也会贡献代码到这个项目一起完善功能。

非常感谢，我这个Go新手在关公面前刷达到了，😁  谢谢！
