### ISSUE TITLE
我靠，终于找到了，大佬牛皮

### ISSUE THREAD

**Issue by nbnb666888** [taoes/SimpleDocker#2]
一直在找这种简单的docker面板管理工具，本人只是熟悉docker，对docker命令并不了解，有时候安装一些docker应用都是复制黏贴代码，不想敲代码，大佬牛皮，希望一直维护下去。

**Comment by taoes** [comment]
会的，但是在需求这些方面需要多多反馈

**Comment by nbnb666888** [comment]
![image](https://user-images.githubusercontent.com/68323911/107202210-e3587180-6a34-11eb-878e-f70ea35fdd42.png)
使用Linux那个教程安装后，执行启动代码报错，大佬看下这是怎么回事？

**Comment by taoes** [comment]
麻烦看一下 ~/.local/simpleDocker 这个目录的文件

**Comment by taoes** [comment]
建议直接使用docker容器启动 `docker run  -d -p 8080:4050 -v /var/run/docker.sock:/var/run/docker.sock --name SimpleDocker  registry.cn-shanghai.aliyuncs.com/seven-tao/simple-docker:0.0.3` 一键启动

**Comment by nbnb666888** [comment]
![image](https://user-images.githubusercontent.com/68323911/107203524-8362ca80-6a36-11eb-814d-48e88704192d.png)
重新安装会报错，

使用docker安装可以打开了。看来命令行运行还存在Bug，谢谢大佬

**Comment by taoes** [comment]
可能是脚本不兼容，可以手动安装下

1. 通过 https://gitee.com/taoes_admin/SimpleDocker/attach_files/587034/download/SimpleDocker-0.0.3-linux.zip  下载最新发布的版本
2. 创建文件夹 ~/.local/simpleDocker 并解压文件,将解压后的文件复制到 ~/.local/simpleDocker 目录
3. 将文件夹 ~/.local/simpleDocker 配置到环境变量 PATH中(可选)
4. 在 ~/.local/simpleDocker下执行 `./simpleDocker` 前端启动 或者 `nohup ./simpleDocker &` 后台启动

> 注意: 一定要解压后的文件放到 ~/.local/simpleDocker 下，否则会出现容器文件浏览功能无法使用，nohup 启动后直接ctrl + c 关闭即可

**Comment by taoes** [comment]
> ![image](https://user-images.githubusercontent.com/68323911/107203524-8362ca80-6a36-11eb-814d-48e88704192d.png)
> 重新安装会报错，
> 
> 使用docker安装可以打开了。看来命令行运行还存在Bug，谢谢大佬

好的，有需求欢迎提Issues

**Comment by nbnb666888** [comment]
请问如何拉取镜像，比如我要安装mysql，人家代码是这样的：（docker run --name dockermysql -p 13306:3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=tank -e MYSQL_USER=tank -e MYSQL_PASSWORD=tank123 -v ~/data/dockermysql:/var/lib/mysql -d mysql:5.7
） 那么我这个地方是怎么填呢？纯小白，希望大佬解答一下
![image](https://user-images.githubusercontent.com/68323911/107206012-7abfc380-6a39-11eb-880d-e0424a7efa9b.png)

**Comment by nbnb666888** [comment]
![image](https://user-images.githubusercontent.com/68323911/107206642-44cf0f00-6a3a-11eb-8e51-c49baffa72bb.png)
还有这里，我重启了容器，但是这个次数还是0，有Bug

**Comment by nbnb666888** [comment]
![image](https://user-images.githubusercontent.com/68323911/107206993-b9a24900-6a3a-11eb-9b27-ec44ad722cec.png)
这里的启动容器，这些参数可以给个默认值吗？不然对小白用户很不友好。

使用了下这个管理后台，简单便捷，很清楚的展示了当前服务器上docker镜像等信息，就是使用的时候可能需要点docker基础。后续我会慢慢摸索的，大佬牛皮

**Comment by taoes** [comment]
> ![image](https://user-images.githubusercontent.com/68323911/107206993-b9a24900-6a3a-11eb-9b27-ec44ad722cec.png)
> 这里的启动容器，这些参数可以给个默认值吗？不然对小白用户很不友好。
> 
> 使用了下这个管理后台，简单便捷，很清楚的展示了当前服务器上docker镜像等信息，就是使用的时候可能需要点docker基础。后续我会慢慢摸索的，大佬牛皮

好建议，后续我会加上，感谢反馈

**Comment by taoes** [comment]
> ![image](https://user-images.githubusercontent.com/68323911/107206642-44cf0f00-6a3a-11eb-8e51-c49baffa72bb.png)
> 还有这里，我重启了容器，但是这个次数还是0，有Bug

这里会有一个前提是，你的 docker 容器是设置了 restart: Always 或者： restart: on-failure: 3 这类的重启策略后，设置了这个策略之后容器停止则会自动重启，此时这个值才有效，否则一直会为0

**Comment by taoes** [comment]
> mysql:5.7

这里填写 `mysql:5.7` 填写的是镜像的 `REPOSITORY:TAG` 比如 使用 docker images 查看列表

![image](https://user-images.githubusercontent.com/22141049/107210472-2586b080-6a3f-11eb-940d-86a99f2be252.png)

**Comment by taoes** [comment]
> > ![image](https://user-images.githubusercontent.com/68323911/107206993-b9a24900-6a3a-11eb-9b27-ec44ad722cec.png)
> > 这里的启动容器，这些参数可以给个默认值吗？不然对小白用户很不友好。
> > 使用了下这个管理后台，简单便捷，很清楚的展示了当前服务器上docker镜像等信息，就是使用的时候可能需要点docker基础。后续我会慢慢摸索的，大佬牛皮
> 
> 好建议，后续我会加上，感谢反馈

我觉得这个后期我会优化为创建向导的方式，通过步骤条来实现引导创建

**Comment by nbnb666888** [comment]
> > > ![image](https://user-images.githubusercontent.com/68323911/107206993-b9a24900-6a3a-11eb-9b27-ec44ad722cec.png)
> > > 这里的启动容器，这些参数可以给个默认值吗？不然对小白用户很不友好。
> > > 使用了下这个管理后台，简单便捷，很清楚的展示了当前服务器上docker镜像等信息，就是使用的时候可能需要点docker基础。后续我会慢慢摸索的，大佬牛皮
> > 
> > 
> > 好建议，后续我会加上，感谢反馈
> 
> 我觉得这个后期我会优化为创建向导的方式，通过步骤条来实现引导创建

对 这个好，用向导的方式。期待
