### ISSUE TITLE
Why there are three router files?

### ISSUE THREAD

**Issue by k8scat** [taoes/SimpleDocker#5]
![image](https://user-images.githubusercontent.com/55872984/116108499-850f6680-a6e6-11eb-9273-94b0faa15eca.png)

**Comment by k8scat** [comment]
which is the used router file?

**Comment by taoes** [comment]
This is the routing file automatically generated by the program, you can choose to ignore it！I'll add its path to the .gitignore file in my next commit!

**Comment by k8scat** [comment]
Thanks
